pipeline {
    agent any
    tools {
        maven 'Maven 3.6.3'
        jdk 'jdk8'
    }
    stages {
        stage ('Initialize') {
            steps {
                echo "PATH = ${PATH}"
                echo "MAVEN_HOME = ${MAVEN_HOME}"
            }
        }

        stage ('Build') {
            steps {
                sh 'mvn -Dmaven.test.failure.ignore=true install'
            }
            post {
                success {
                    echo "build success"
                    echo `mvn help:evaluate -Dexpression=project.name | grep "^[^\[]"`
                    echo `mvn help:evaluate -Dexpression=project.version | grep "^[^\[]"`
                }
            }
        }
    }
}