pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                echo 'this is a simple pipeline.'
                sh 'mvn -B -DskipTests clean package'
            }
        }
    }
}
